# https://taskfile.dev

version: '3'

# import environment variables from config.yml
dotenv: ['config.yml']

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Build and run go binary.
    cmds:
      - task: build
      - ./$appname

  build:
    desc: Build go binary.
    cmds:
      - go build -o ./$appname ./cmds/main.go
    #silent: true